# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 9090
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    #max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    #min-spare-threads: 30
# Spring配置
spring:
  application:
    name: workflow
  main:
    allow-bean-definition-overriding: true
  liquibase:
    enabled: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  profiles:
    active: dev

  # rabbitmq配置信息
  rabbitmq:
    # ip
    host: localhost
    # 端口
    port: 5672
    # 用户名
    username: tdx
    # 密码
    password: tdx123
    # 配置虚拟机
    virtual-host: /
    #消息发送到交换机确认机制，是否返回回调
    publisher-returns: true
    # 消息开启手动确认
    listener:
      simple:
        retry:
          enabled: true # 开启消费者进行重试
          max-attempts: 5 # 最大重试次数
          initial-interval: 3000 # 重试时间间隔
      direct:
        acknowledge-mode: manual
